image: Visual Studio 2017

before_build:
    - nuget restore

platform:
    # - x86
    # - x64
    - Any CPU

# configuration:
    # - Debug
    # - Release

branches:
    only:
    - master

install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt ../../../../.././misc/.token.enc -secret %my_secret%
  - sh: ./appveyor-tools/secure-file -decrypt ../../../../.././misc/.token.enc -secret $my_secret

environment:
  my_variable:
    secure: rgzDkmzMohFVnVkgMqrUCg==