version: '{build}'

image: Visual Studio 2017

init: git config --global core.autocrlf true

nuget:
  disable_publish_on_pr: true  
  account_feed: true
  project_feed: true

platform:
    # - x86
    # - x64
    - Any CPU

configuration:
    # - Debug
    - Release

branches:
    only:
    - master
    
environment:
  token:
    secure: rgzDkmzMohFVnVkgMqrUCg==

install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt ./misc/.token.enc -secret %token%
  - sh: ./appveyor-tools/secure-file -decrypt ./misc/.token.enc -secret token
  

before_build:
    - nuget restore

build:
    publish_nuget: true

deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: 40rOVDXOWx1TwOU6OcKIkJ/i/8CYwlR0rKMF+yk9uFSbFG9GBQDoqfM/tfZyIPhO #93gf2kld7tie693rw5sqom7e
  skip_symbols: false
  symbol_server: https://ci.appveyor.com/nuget/0x0001f36d-6k7wspxc8l6y/api/v2/package
  artifact: /.*\.nupkg/