image: Visual Studio 2017

before_build:
    - nuget restore

platform:
    # - x86
    # - x64
    - Any CPU

# configuration:
    # - Debug
    # - Release

branches:
    only:
    - master
    
environment:
  token:
    secure: rgzDkmzMohFVnVkgMqrUCg==

install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt ./misc/.token.enc -secret %token%
  - sh: ./appveyor-tools/secure-file -decrypt ./misc/.token.enc -secret token
